language: cpp

env:
  - LUA_VERSION=5.3.2 COMPILER=g++-4.8
  - LUA_VERSION=5.2.4 COMPILER=g++-4.8
  - LUA_VERSION=5.1.5 COMPILER=g++-4.8

  - LUA_VERSION=5.3.2 COMPILER=g++-4.9
  - LUA_VERSION=5.2.4 COMPILER=g++-4.9
  - LUA_VERSION=5.1.5 COMPILER=g++-4.9

  - LUA_VERSION=5.3.2 COMPILER=g++-5
  - LUA_VERSION=5.2.4 COMPILER=g++-5
  - LUA_VERSION=5.1.5 COMPILER=g++-5

  - LUA_VERSION=5.3.2 COMPILER=g++-6
  - LUA_VERSION=5.2.4 COMPILER=g++-6
  - LUA_VERSION=5.1.5 COMPILER=g++-6

  - LUA_VERSION=5.3.2 COMPILER=clang++-3.7
  - LUA_VERSION=5.2.4 COMPILER=clang++-3.7
  - LUA_VERSION=5.1.5 COMPILER=clang++-3.7

cache:
  directories:
    - lua-$LUA_VERSION

before_install:
  - export CXX=$COMPILER

install:
  # Build Lua
  - test -e "lua-$LUA_VERSION/src" || (wget "http://www.lua.org/ftp/lua-$LUA_VERSION.tar.gz" && tar xvfz "lua-$LUA_VERSION.tar.gz")
  - pushd "lua-$LUA_VERSION/src"
  - test -e liblua-custom.a || make LUA_A=liblua-custom.a linux
  - export "LUA_SOURCE_PATH=$(pwd)"
  - popd

script:
  - make "LUA_LIBDIR=$LUA_SOURCE_PATH" "LUA_INCDIR=$LUA_SOURCE_PATH" LUA_LIBNAME=lua-custom all

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      - make
      - wget
      - clang-3.7
      - g++-4.8
      - g++-4.9
      - g++-5
      - g++-6
