site_name: Luwra
site_description: Minimal-overhead Lua wrapper for C++
repo_url: https://github.com/vapourismo/luwra
pages:
  - 'Home': index.md
  - 'Basics': basics.md
  - 'Advanced Stack Interaction': advanced.md
  - 'Wrapping': wrapping.md
  - 'User Types': user-types.md
theme: readthedocs
docs_dir: docs/mkdocs
site_dir: docs/output
